### ISSUE TITLE
Version 1.0.0 First Phase

### ISSUE THREAD

**Issue by tvhoang91** [tvhoang91/hoangapp#1]
### Task

- [ ] Setup process: sass, netlify
- [ ] Layout: SideNav, Cover, Portfolio, Faqs, Contact
- [ ] Content: Faqs, Social Links
- [ ] React Animation: SideNav responsive, Faqs accordion

### Reference

https://www.youtube.com/watch?v=gYzHS-n2gqU&list=PLillGF-RfqbYoGoCjKoMOkVznV6aSXKzU
